image: node:latest

stages:
  - install
  - build
  - package

cache:
  paths:
    - node_modules/

install_dependencies:
  stage: install
  script:
    - npm install
  only:
    - main
    - tags

build_project:
  stage: build
  script:
    - npx webpack --config webpack.config.js
  artifacts:
    paths:
      - dist/
  only:
    - main
    - tags

package_extension:
  stage: package
  script:
    - apt-get update && apt-get install -y zip
    - TAG_NAME=$(git describe --tags --exact-match || echo "latest")  # latest
    - mkdir -p releases
    - zip -r "releases/yolo-image-annotator-$TAG_NAME.zip" icons/ popup/ scripts/ styles/ options.html options.js manifest.json dist/
  artifacts:
    paths:
      - "releases/yolo-image-annotator-*.zip"
  only:
    - main
    - tags
    
release:
  stage: release
  script:
    - |
      curl --request POST --header "PRIVATE-TOKEN: $CI_JOB_TOKEN" \
      --data "name=Release $CI_COMMIT_TAG" \
      --data "tag_name=$CI_COMMIT_TAG" \
      --data "description=Automated release for $CI_COMMIT_TAG\n\nDownload the attached zip file, extract it, and load it as an unpacked extension in Chrome or Firefox." \
      --data "assets[links][][name]=Download ZIP" \
      --data "assets[links][][url]=$CI_PROJECT_URL/-/jobs/$CI_JOB_ID/artifacts/download" \
      "$CI_API_V4_URL/projects/$CI_PROJECT_ID/releases"
  only:
    - tags
