image: node:latest

stages:
  - install
  - build
  - package
  - release

cache:
  paths:
    - node_modules/

install_dependencies:
  stage: install
  script:
    - npm install
  only:
    - main
    - tags

build_project:
  stage: build
  script:
    - npx webpack --config webpack.config.js
  artifacts:
    paths:
      - dist/
  only:
    - main
    - tags

package_extension:
  stage: package
  script:
    - apt-get update && apt-get install -y zip
    - TAG_NAME=$(git describe --tags --exact-match || echo "latest")  # latest
    - mkdir -p releases
    - zip -r "releases/yolo-image-annotator-$TAG_NAME.zip" icons/ popup/ scripts/ styles/ options.html options.js manifest.json dist/
  artifacts:
    paths:
      - "releases/yolo-image-annotator-*.zip"
  only:
    - main
    - tags

release:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  script:
    - echo "Creating release for tag $CI_COMMIT_TAG"
  release:
    name: "Release $CI_COMMIT_TAG"
    description: "Automated release for $CI_COMMIT_TAG\n\nDownload the attached zip file, extract it, and load it as an unpacked extension in Chrome or Firefox."
    tag_name: "$CI_COMMIT_TAG"
    ref: "$CI_COMMIT_SHA"
    assets:
      links:
        - name: "Download ZIP"
          url: "$CI_PROJECT_URL/-/jobs/$CI_JOB_ID/artifacts/download"
  only:
    - tags