image: node:latest

stages:
  - install
  - build
  - package

cache:
  paths:
    - node_modules/

install_dependencies:
  stage: install
  script:
    - npm install
  only:
    - main
    - tags

build_project:
  stage: build
  script:
    - npx webpack --config webpack.config.js
  artifacts:
    paths:
      - dist/
  only:
    - main
    - tags

package_extension:
  stage: package
  script:
    - apt-get update && apt-get install -y zip
    - TAG_NAME=$(git describe --tags --exact-match || echo "latest")  # latest
    - mkdir -p releases
    - zip -r "releases/yolo-image-annotator-$TAG_NAME.zip" icons/ popup/ scripts/ styles/ options.html options.js manifest.json dist/
  artifacts:
    paths:
      - "releases/yolo-image-annotator-*.zip"
  only:
    - main
    - tags
